import type { Metadata } from "next";
import { Inter, Google_Sans_Flex } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v16-appRouter";
import MuiThemeWrapper from "@/components/wrappers/theme";
import { NextIntlClientProvider } from "next-intl";
import { PropsWithChildren } from "react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const google_sans_flex = Google_Sans_Flex({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-google-sans-flex",
});

export const metadata: Metadata = {
  title: "thinh26 | Navigation Hub",
  description: "Generated by thinh26.",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<
  PropsWithChildren & {
    params: Promise<{ locale: string }>;
  }
>) {
  const { locale } = await params;

  return (
    <html lang={locale}>
      <body className={`${google_sans_flex.variable} ${inter.variable}`}>
        <AppRouterCacheProvider>
          <NextIntlClientProvider>
            <MuiThemeWrapper>{children}</MuiThemeWrapper>
          </NextIntlClientProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
